title: Geo Conference Deadlines # (Maintained by @LukasMosser, Original by @abshkdz)
# email: lukas.mosser@gmail.com
description: Countdowns to top geoscience & engineering conference deadlines
author: Lukas Mosser (Original by Abhishek Das)

domain: "geodeadlin.es"
baseurl: ""

twitter_username: porestar
twitter_hashtag: geoscience
github_username: lukasmosser
github_repo: geo-deadlines

markdown: kramdown
ga_id: UA-114722448-1
